// FNAF Save Manager - Interactive Script
(function(){
"use strict";

// === TRANSLATIONS ===
const T = {
en: { nav_features:"Features",nav_games:"Games",nav_capabilities:"Capabilities",nav_roadmap:"Roadmap",nav_download:"Download",hero_badge:"17 Games Supported",hero_title_1:"FNAF Save Manager",hero_title_2:"& Editor",hero_subtitle:"The ultimate save editor for Five Nights at Freddy\'s. Modify save files, unlock nights, earn stars, and explore hidden content across the entire franchise.",hero_download:"Download Latest",hero_gamejolt:"View on GameJolt",hero_scroll:"Scroll to explore",features_label:"Core Features",features_title:"Everything You Need to Manage Your FNAF Saves",features_desc:"A comprehensive toolkit built for the FNAF community, providing powerful save modification, backup, and restoration capabilities.",f1_title:"Unlock Everything",f1_desc:"Quickly modify supported progression and unlockable content across all 17 supported game configurations with a single click.",f2_title:"Save Backup & Restore",f2_desc:"Create secure backups before modifying any save files. Restore previous states at any time to keep your progress safe.",f3_title:"Automatic Game Detection",f3_desc:"The tool automatically detects supported game data on your system, so you can start editing without manual configuration.",f4_title:"Direct Save Editing",f4_desc:"Modify supported values directly through the clean graphical interface. Edit nights, stars, ratings, cash, and more.",f5_title:"Easter Eggs & Extras",f5_desc:"Toggle supported hidden events, secret content, and special game data that are normally difficult to access.",f6_title:"Modern UI",f6_desc:"A clean, intuitive graphical interface built with PySide6. Designed for ease of use and a professional experience.",games_label:"Supported Games",games_title:"17 Game Configurations Available",games_desc:"Full support for standard .ini save files generated by the Clickteam Fusion engine across the FNAF franchise and selected fangames.",cap_label:"Core Capabilities",cap_title:"Powerful Tools at Your Fingertips",cap_desc:"Every capability designed to give you full control over your FNAF save data with a focus on safety and simplicity.",road_label:"Roadmap",road_title:"Future Updates & Plans",road_desc:"We are actively working on expanding the capabilities of the FNAF Save Manager with new features and game support.",save_label:"Save File Location",save_title:"Where Are FNAF Save Files?",save_desc:"The FNAF Save Manager automatically detects supported game data whenever possible. If you need to locate the files manually:",save_hint:"Standard Clickteam Fusion FNAF save data is commonly stored in:",tech_label:"Built With",tech_title:"Technology Stack",tech_desc:"A powerful combination of technologies delivering a reliable save management experience.",dl_label:"Download",dl_title:"Get FNAF Save Manager",dl_desc:"Download the latest version from GitHub Releases or GameJolt. The installer provides a simple setup process for Windows users.",cr_label:"Creator",cr_title:"Meet the Developer",cr_desc:"Created with dedication by K_F_, also known as kiyanfnaflover-ui.",disc_title:"Disclaimer",disc_text:"This project is intended for educational and personal use. FNAF Save Manager is not affiliated with, endorsed by, or sponsored by Scott Cawthon or the owners of the Five Nights at Freddy\'s franchise. Please support the official Five Nights at Freddy\'s games and their creators by purchasing and playing the official releases.",footer_text:"Made with dedication by K_F_" },
es: { nav_features:"Caracteristicas",nav_games:"Juegos",nav_capabilities:"Capacidades",nav_roadmap:"Hoja de Ruta",nav_download:"Descargar",hero_badge:"17 Juegos Soportados",hero_title_1:"FNAF Save Manager",hero_title_2:"& Editor",hero_subtitle:"El editor definitivo para Five Nights at Freddy\'s. Modifica archivos, desbloquea noches y explora contenido oculto.",hero_download:"Descargar",hero_gamejolt:"Ver en GameJolt",hero_scroll:"Desplazar",features_label:"Caracteristicas",features_title:"Todo lo que Necesitas",features_desc:"Un kit de herramientas para la comunidad FNAF con capacidades de modificacion, respaldo y restauracion.",f1_title:"Desbloquear Todo",f1_desc:"Modifica rapidamente la progresion y contenido desbloqueable en las 17 configuraciones de juego.",f2_title:"Respaldo y Restauracion",f2_desc:"Crea respaldos seguros antes de modificar. Restaura estados anteriores en cualquier momento.",f3_title:"Deteccion Automatica",f3_desc:"Detecta automaticamente los datos de juego soportados en tu sistema.",f4_title:"Edicion Directa",f4_desc:"Modifica valores directamente a traves de la interfaz grafica.",f5_title:"Easter Eggs",f5_desc:"Activa eventos ocultos y contenido secreto normalmente dificil de acceder.",f6_title:"Interfaz Moderna",f6_desc:"Una interfaz limpia e intuitiva construida con PySide6.",games_label:"Juegos Soportados",games_title:"17 Configuraciones",games_desc:"Soporte completo para archivos .ini del motor Clickteam Fusion.",cap_label:"Capacidades",cap_title:"Herramientas Poderosas",cap_desc:"Cada capacidad disenada para darte control total sobre tus datos.",road_label:"Hoja de Ruta",road_title:"Actualizaciones Futuras",road_desc:"Trabajamos activamente en expandir las capacidades del gestor.",save_label:"Ubicacion de Archivos",save_title:"Donde estan los Archivos?",save_desc:"El gestor detecta automaticamente los datos. Si necesitas ubicarlos manualmente:",save_hint:"Los datos de guardado de FNAF generalmente se encuentran en:",tech_label:"Tecnologias",tech_title:"Stack Tecnologico",tech_desc:"Una combinacion poderosa de tecnologias.",dl_label:"Descargar",dl_title:"Obtener FNAF Save Manager",dl_desc:"Descarga la ultima version desde GitHub Releases o GameJolt.",cr_label:"Creador",cr_title:"Conoce al Desarrollador",cr_desc:"Creado con dedicacion por K_F_.",disc_title:"Aviso Legal",disc_text:"Este proyecto es para uso educativo y personal. No esta afiliado con Scott Cawthon ni los propietarios de Five Nights at Freddy\'s.",footer_text:"Hecho con dedicacion por K_F_" },
fr: { nav_features:"Fonctionnalites",nav_games:"Jeux",nav_capabilities:"Capacites",nav_roadmap:"Feuille de route",nav_download:"Telecharger",hero_badge:"17 Jeux Supportes",hero_title_1:"FNAF Save Manager",hero_title_2:"& Editeur",hero_subtitle:"L\'editeur ultime pour Five Nights at Freddy\'s. Modifiez les sauvegardes, debloquez les nuits et explorez le contenu cache.",hero_download:"Telecharger",hero_gamejolt:"Voir sur GameJolt",hero_scroll:"Defiler",features_label:"Fonctionnalites",features_title:"Tout ce dont vous avez besoin",features_desc:"Une boite a outils complete pour la communaute FNAF.",f1_title:"Tout Debloquer",f1_desc:"Modifiez rapidement la progression sur les 17 configurations.",f2_title:"Sauvegarde & Restauration",f2_desc:"Creez des sauvegardes securisees avant toute modification.",f3_title:"Detection Automatique",f3_desc:"Detecte automatiquement les donnees de jeu.",f4_title:"Edition Directe",f4_desc:"Modifiez les valeurs directement via l\'interface.",f5_title:"Easter Eggs",f5_desc:"Activez les evenements caches et contenu secret.",f6_title:"Interface Moderne",f6_desc:"Une interface propre construite avec PySide6.",games_label:"Jeux Supportes",games_title:"17 Configurations",games_desc:"Support complet des fichiers .ini Clickteam Fusion.",cap_label:"Capacites",cap_title:"Outils Puissants",cap_desc:"Chaque capacite concue pour vous donner un controle total.",road_label:"Feuille de route",road_title:"Mises a jour Futures",road_desc:"Nous travaillons a etendre les capacites du gestionnaire.",save_label:"Emplacement",save_title:"Ou sont les Fichiers?",save_desc:"Le gestionnaire detecte automatiquement. Si necessaire:",save_hint:"Les sauvegardes FNAF se trouvent generalement dans:",tech_label:"Technologies",tech_title:"Stack Technique",tech_desc:"Une combinaison puissante de technologies.",dl_label:"Telecharger",dl_title:"Obtenir FNAF Save Manager",dl_desc:"Telechargez depuis GitHub Releases ou GameJolt.",cr_label:"Createur",cr_title:"Le Developpeur",cr_desc:"Cree avec dedication par K_F_.",disc_title:"Avertissement",disc_text:"Ce projet est pour usage educatif et personnel. Non affilie a Scott Cawthon.",footer_text:"Fait avec dedication par K_F_" },
de: { nav_features:"Funktionen",nav_games:"Spiele",nav_capabilities:"Fahigkeiten",nav_roadmap:"Fahrplan",nav_download:"Herunterladen",hero_badge:"17 Spiele Unterstutzt",hero_title_1:"FNAF Save Manager",hero_title_2:"& Editor",hero_subtitle:"Der ultimative Save-Editor fur Five Nights at Freddy\'s.",hero_download:"Herunterladen",hero_gamejolt:"Auf GameJolt ansehen",hero_scroll:"Scrollen",features_label:"Funktionen",features_title:"Alles was Sie brauchen",features_desc:"Ein umfassendes Toolkit fur die FNAF-Community.",f1_title:"Alles Freischalten",f1_desc:"Modifizieren Sie schnell die Fortschritte in 17 Spielkonfigurationen.",f2_title:"Sicherung & Wiederherstellung",f2_desc:"Erstellen Sie sichere Backups vor jeder Anderung.",f3_title:"Automatische Erkennung",f3_desc:"Erkennt automatisch unterstutzte Spieldaten.",f4_title:"Direkte Bearbeitung",f4_desc:"Modifizieren Sie Werte direkt uber die Oberflache.",f5_title:"Easter Eggs",f5_desc:"Aktivieren Sie versteckte Ereignisse und Geheimnisse.",f6_title:"Moderne UI",f6_desc:"Eine saubere, intuitive Oberflache mit PySide6.",games_label:"Unterstutzte Spiele",games_title:"17 Konfigurationen",games_desc:"Vollstandige Unterstutzung fur .ini-Dateien von Clickteam Fusion.",cap_label:"Fahigkeiten",cap_title:"Leistungsstarke Werkzeuge",cap_desc:"Jede Funktion fur volle Kontrolle uber Ihre Spieldaten.",road_label:"Fahrplan",road_title:"Zukunftige Updates",road_desc:"Wir erweitern aktiv die Fahigkeiten des Save Managers.",save_label:"Speicherort",save_title:"Wo sind die Dateien?",save_desc:"Der Manager erkennt automatisch. Bei Bedarf:",save_hint:"FNAF-Savedaten befinden sich meist in:",tech_label:"Technologien",tech_title:"Tech-Stack",tech_desc:"Eine leistungsstarke Technologiekombination.",dl_label:"Herunterladen",dl_title:"FNAF Save Manager",dl_desc:"Laden Sie die neueste Version von GitHub oder GameJolt.",cr_label:"Entwickler",cr_title:"Der Entwickler",cr_desc:"Mit Hingabe erstellt von K_F_.",disc_title:"Haftungsausschluss",disc_text:"Dieses Projekt ist fur bildungliche und personliche Nutzung. Nicht affiliiert mit Scott Cawthon.",footer_text:"Mit Hingabe gemacht von K_F_" },
pt: { nav_features:"Funcionalidades",nav_games:"Jogos",nav_capabilities:"Capacidades",nav_roadmap:"Roteiro",nav_download:"Baixar",hero_badge:"17 Jogos Suportados",hero_title_1:"FNAF Save Manager",hero_title_2:"& Editor",hero_subtitle:"O editor definitivo para Five Nights at Freddy\'s.",hero_download:"Baixar",hero_gamejolt:"Ver no GameJolt",hero_scroll:"Rolar",features_label:"Funcionalidades",features_title:"Tudo que voce precisa",features_desc:"Um kit de ferramentas completo para a comunidade FNAF.",f1_title:"Desbloquear Tudo",f1_desc:"Modifique rapidamente a progressao em 17 configuracoes.",f2_title:"Backup & Restauracao",f2_desc:"Crie backups seguros antes de modificar.",f3_title:"Deteccao Automatica",f3_desc:"Detecta automaticamente os dados do jogo.",f4_title:"Edicao Direta",f4_desc:"Modifique valores diretamente pela interface.",f5_title:"Easter Eggs",f5_desc:"Ative eventos ocultos e conteudo secreto.",f6_title:"Interface Moderna",f6_desc:"Uma interface limpa construida com PySide6.",games_label:"Jogos Suportados",games_title:"17 Configuracoes",games_desc:"Suporte completo para arquivos .ini do Clickteam Fusion.",cap_label:"Capacidades",cap_title:"Ferramentas Poderosas",cap_desc:"Cada capacidade projetada para controle total.",road_label:"Roteiro",road_title:"Atualizacoes Futuras",road_desc:"Estamos expandindo ativamente as capacidades.",save_label:"Local de Arquivos",save_title:"Onde estao os Arquivos?",save_desc:"O gerenciador detecta automaticamente. Se necessario:",save_hint:"Os dados de FNAF geralmente estao em:",tech_label:"Tecnologias",tech_title:"Stack Tecnologico",tech_desc:"Uma combinacao poderosa de tecnologias.",dl_label:"Baixar",dl_title:"Obter FNAF Save Manager",dl_desc:"Baixe a ultima versao do GitHub ou GameJolt.",cr_label:"Criador",cr_title:"O Desenvolvedor",cr_desc:"Criado com dedicacao por K_F_.",disc_title:"Aviso Legal",disc_text:"Este projeto e para uso educacional e pessoal. Nao afiliado a Scott Cawthon.",footer_text:"Feito com dedicacao por K_F_" },
ja: { nav_features:"Features",nav_games:"Games",nav_capabilities:"Capabilities",nav_roadmap:"Roadmap",nav_download:"Download",hero_badge:"17 Games Supported",hero_title_1:"FNAF Save Manager",hero_title_2:"& Editor",hero_subtitle:"Five Nights at Freddy\'s no tame no saishuu no save editor.",hero_download:"Download",hero_gamejolt:"GameJolt de miru",hero_scroll:"Scroll",features_label:"Features",features_title:"FNAF Save wo Kanri Suru Subete",features_desc:"FNAF community no tame no sogu toolkit.",f1_title:"Subete Kaijo",f1_desc:"17 no game configuration ni taiou.",f2_title:"Backup & Restore",f2_desc:"Anzen na backup wo sakusei.",f3_title:"Jidou Kenshutsu",f3_desc:"Game data wo jidou kenshutsu.",f4_title:"Chokusetsu Henshu",f4_desc:"Interface kara chokusetsu hen shu.",f5_title:"Easter Eggs",f5_desc:"Kakushi content wo kaijo.",f6_title:"Modern UI",f6_desc:"PySide6 de kouchiku.",games_label:"Supported Games",games_title:"17 Configurations",games_desc:"Clickteam Fusion .ini files ni taiou.",cap_label:"Capabilities",cap_title:"Powerful Tools",cap_desc:"Subete no kinou ga full control wo teikyou.",road_label:"Roadmap",road_title:"Future Updates",road_desc:"Shinou kinou no kaihatsu chu.",save_label:"Save Location",save_title:"Save Files no Basho",save_desc:"Jidou kenshutsu kanou. Manual ni hitsuyou na baai:",save_hint:"FNAF save data wa ippan teki ni:",tech_label:"Built With",tech_title:"Technology Stack",tech_desc:"Tsuyoi gijutsu no kumiawase.",dl_label:"Download",dl_title:"FNAF Save Manager wo Get",dl_desc:"GitHub ka GameJolt kara download.",cr_label:"Creator",cr_title:"Developer",cr_desc:"K_F_ ni yotte sakusei.",disc_title:"Disclaimer",disc_text:"Kyoiku to koji you. Scott Cawthon to wa kanren arimasen.",footer_text:"K_F_ ni yotte tsukurareta" },
zh: { nav_features:"Features",nav_games:"Games",nav_capabilities:"Capabilities",nav_roadmap:"Roadmap",nav_download:"Download",hero_badge:"17 Games Supported",hero_title_1:"FNAF Save Manager",hero_title_2:"& Editor",hero_subtitle:"Wu zhi xiao ye de zui zhong ji save editor.",hero_download:"Download",hero_gamejolt:"GameJolt",hero_scroll:"Scroll",features_label:"Features",features_title:"FNAF Save de Subete",features_desc:"FNAF community no tame no toolkit.",f1_title:"Kaijo Subete",f1_desc:"17 no configuration ni taiou.",f2_title:"Backup & Restore",f2_desc:"Safe backup wo sakusei.",f3_title:"Jidou Kenshutsu",f3_desc:"Jidou de game data wo kenshutsu.",f4_title:"Chokusetsu Henshu",f4_desc:"Interface kara chokusetsu henshu.",f5_title:"Easter Eggs",f5_desc:"Kakushi content wo kaijo.",f6_title:"Modern UI",f6_desc:"PySide6 de kouchiku.",games_label:"Supported Games",games_title:"17 Configurations",games_desc:"Clickteam Fusion .ini ni taiou.",cap_label:"Capabilities",cap_title:"Powerful Tools",cap_desc:"Full control wo teikyou.",road_label:"Roadmap",road_title:"Future Updates",road_desc:"Shinou kinou kaihatsu chu.",save_label:"Save Location",save_title:"Save Files no Basho",save_desc:"Jidou kenshutsu kanou. Manual hitsuyu baai:",save_hint:"FNAF save data wa:",tech_label:"Built With",tech_title:"Technology Stack",tech_desc:"Gijutsu no kumiawase.",dl_label:"Download",dl_title:"FNAF Save Manager",dl_desc:"GitHub ka GameJolt kara.",cr_label:"Creator",cr_title:"Developer",cr_desc:"K_F_ ni yori sakusei.",disc_title:"Disclaimer",disc_text:"Kyoiku to shiyou. Scott Cawthon to wa mukankei.",footer_text:"K_F_ ni yori tsukurareta" },
ko: { nav_features:"Features",nav_games:"Games",nav_capabilities:"Capabilities",nav_roadmap:"Roadmap",nav_download:"Download",hero_badge:"17 Games Supported",hero_title_1:"FNAF Save Manager",hero_title_2:"& Editor",hero_subtitle:"Five Nights at Freddy\'s ui choe go save editor.",hero_download:"Download",hero_gamejolt:"GameJolt eseo bogi",hero_scroll:"Scroll",features_label:"Features",features_title:"FNAF Save gwanli ui je mo geos",features_desc:"FNAF community wi toolkit.",f1_title:"Modeun geos Haedal",f1_desc:"17 gae configuration jeogwon.",f2_title:"Backup & Restore",f2_desc:"Anjeonhan backup seongseong.",f3_title:"Jadong Gyechal",f3_desc:"Game data jadong gyechal.",f4_title:"Jikjeok Pyeon-gi",f4_desc:"Interface eseojikjeok pyeongi.",f5_title:"Easter Eggs",f5_desc:"Sagye content haedal.",f6_title:"Modern UI",f6_desc:"PySide6 euo geonseol.",games_label:"Supported Games",games_title:"17 Configurations",games_desc:"Clickteam Fusion .ini jeogwon.",cap_label:"Capabilities",cap_title:"Powerful Tools",cap_desc:"Full control je gong geun.",road_label:"Roadmap",road_title:"Future Updates",road_desc:"Sineo gineung gaebal jung.",save_label:"Save Location",save_title:"Save File i Eodi issneunga",save_desc:"Jadong gyechal ganeung. Pil yo si:",save_hint:"FNAF save data neun:",tech_label:"Built With",tech_title:"Technology Stack",tech_desc:"Gigyeok ui jo hap.",dl_label:"Download",dl_title:"FNAF Save Manager",dl_desc:"GitHub hwa GameJolt eseon.",cr_label:"Creator",cr_title:"Developer",cr_desc:"K_F_ euijeong euo jejak.",disc_title:"Disclaimer",disc_text:"Gyoyuk jeok mokjeok. Scott Cawthon gwan ryeon eobsseum.",footer_text:"K_F_ euijeong euo mandeul eossseum" },
ru: { nav_features:"Funkcii",nav_games:"Igry",nav_capabilities:"Vozmozhnosti",nav_roadmap:"Plan",nav_download:"Skachat",hero_badge:"17 Podderzhivaemykh Igr",hero_title_1:"FNAF Save Manager",hero_title_2:"& Redaktor",hero_subtitle:"Ultimativnyi redaktor sohranenij dlya Five Nights at Freddy\'s.",hero_download:"Skachat",hero_gamejolt:"Na GameJolt",hero_scroll:"Prokrutit",features_label:"Funkcii",features_title:"Vse dlya upravleniya sohraneniyami FNAF",features_desc:"Kompleksnyi nabor instrumentov dlya soobshchestva FNAF.",f1_title:"Razblokirovat Vse",f1_desc:"Bystro izmenite progress vo vseh 17 konfiguratsiyakh.",f2_title:"Rezervnoe Kopirovanie",f2_desc:"Sozdayte bezopasnye kopii pered izmeneniyami.",f3_title:"Avtomaticheskoe Opredelenie",f3_desc:"Avtomaticheski opredelyaet dannye igry.",f4_title:"Pryamoe Redaktirovanie",f4_desc:"Izmenyayte znacheniya cherez interfeis.",f5_title:"Paskhalnye Yajca",f5_desc:"Vklyuchite skrytye sobytiya i sekretnyi kontent.",f6_title:"Sovremennyi Interfeis",f6_desc:"Chistyj interfeis na PySide6.",games_label:"Podderzhivaemye Igry",games_title:"17 Konfiguratsij",games_desc:"Polnaya podderzhka .ini fajlov Clickteam Fusion.",cap_label:"Vozmozhnosti",cap_title:"Moshchnye Instrumenty",cap_desc:"Každyj instrument dlya polnogo kontrolya.",road_label:"Plan",road_title:"Budushchie Obnovleniya",road_desc:"My aktivno rasshiryaem vozmozhnosti.",save_label:"Mestopolozhenie",save_title:"Gde nakhodyatsya fajly sohranenij?",save_desc:"Menedzher opredelyaet avtomaticheski. Pri neobkhodimosti:",save_hint:"Dannye sohranenij FNAF obychno nakhodyatsya v:",tech_label:"Tekhnologii",tech_title:"Tekhnologicheskij Stack",tech_desc:"Moshchnaya kombinatsiya tekhnologij.",dl_label:"Skachat",dl_title:"Poluchit FNAF Save Manager",dl_desc:"Skachayte s GitHub Releases ili GameJolt.",cr_label:"Sozdatel",cr_title:"Razrabot",cr_desc:"Sozdano s otdachej K_F_.",disc_title:"Otvets tvennost",disc_text:"Proekt dlya obrazovatelnykh i lichnykh tselej. Ne affiliirovano s Scott Cawthon.",footer_text:"Sdelano s otdachej K_F_" }
};

// === LANGUAGE SYSTEM ===
let currentLang = 'en';
function getUrlLang(){ const p=new URLSearchParams(window.location.search); return p.get('lang'); }
function setLang(lang){
    if(!T[lang]) lang='en';
    currentLang=lang;
    document.documentElement.lang=lang;
    document.getElementById('currentLang').textContent=lang.toUpperCase();
    document.querySelectorAll('[data-i18n]').forEach(el=>{
        const key=el.getAttribute('data-i18n');
        if(T[lang][key]) el.textContent=T[lang][key];
    });
    localStorage.setItem('fnafsm_lang',lang);
}
function initLang(){
    const urlLang=getUrlLang();
    const savedLang=localStorage.getItem('fnafsm_lang');
    setLang(urlLang||savedLang||'en');
}

// === LANGUAGE DROPDOWN ===
const langBtn=document.getElementById('langBtn');
const langDrop=document.getElementById('langDropdown');
langBtn.addEventListener('click',e=>{e.stopPropagation();langDrop.classList.toggle('active');});
document.addEventListener('click',()=>langDrop.classList.remove('active'));
langDrop.querySelectorAll('.lang-option').forEach(btn=>{
    btn.addEventListener('click',()=>{setLang(btn.dataset.lang);langDrop.classList.remove('active');});
});

// === NAVBAR SCROLL ===
const navbar=document.getElementById('navbar');
window.addEventListener('scroll',()=>{navbar.classList.toggle('scrolled',window.scrollY>50);},{passive:true});

// === MOBILE MENU ===
const navToggle=document.getElementById('navToggle');
const navLinks=document.getElementById('navLinks');
navToggle.addEventListener('click',()=>{navToggle.classList.toggle('active');navLinks.classList.toggle('active');});
navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navToggle.classList.remove('active');navLinks.classList.remove('active');}));

// === 3D TILT EFFECT ===
function initTilt(){
    document.querySelectorAll('[data-tilt]').forEach(card=>{
        card.addEventListener('mousemove',e=>{
            const rect=card.getBoundingClientRect();
            const x=e.clientX-rect.left;
            const y=e.clientY-rect.top;
            const cx=rect.width/2; const cy=rect.height/2;
            const rx=((y-cy)/cy)*-8;
            const ry=((x-cx)/cx)*8;
            card.style.transform=`perspective(1000px) rotateX(${rx}deg) rotateY(${ry}deg) scale3d(1.02,1.02,1.02)`;
        });
        card.addEventListener('mouseleave',()=>{
            card.style.transform='perspective(1000px) rotateX(0) rotateY(0) scale3d(1,1,1)';
        });
    });
}

// === HERO CARD 3D ===
function initHeroCard(){
    const card=document.getElementById('heroCard');
    const shine=card.querySelector('.card-shine');
    if(!card) return;
    document.addEventListener('mousemove',e=>{
        const rect=card.getBoundingClientRect();
        const cx=rect.left+rect.width/2;
        const cy=rect.top+rect.height/2;
        const dx=(e.clientX-cx)/(rect.width/2);
        const dy=(e.clientY-cy)/(rect.height/2);
        card.style.transform=`perspective(1000px) rotateY(${dx*10}deg) rotateX(${-dy*10}deg) translateZ(20px)`;
        shine.style.setProperty('--shine-x',((e.clientX-rect.left)/rect.width*100)+'%');
        shine.style.setProperty('--shine-y',((e.clientY-rect.top)/rect.height*100)+'%');
    });
}

// === PARTICLES ===
function initParticles(){
    const container=document.getElementById('heroParticles');
    if(!container) return;
    for(let i=0;i<40;i++){
        const p=document.createElement('div');
        p.className='particle';
        p.style.left=Math.random()*100+'%';
        p.style.top=Math.random()*100+'%';
        p.style.animationDelay=Math.random()*4+'s';
        p.style.animationDuration=(3+Math.random()*3)+'s';
        const size=1+Math.random()*2;
        p.style.width=size+'px';
        p.style.height=size+'px';
        if(Math.random()>0.5) p.style.background='var(--accent-cyan)';
        container.appendChild(p);
    }
}

// === SCROLL REVEAL ===
function initReveal(){
    const observer=new IntersectionObserver((entries)=>{
        entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}});
    },{threshold:0.1,rootMargin:'0px 0px -40px 0px'});
    document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
}

// === SMOOTH SCROLL ===
function initSmoothScroll(){
    document.querySelectorAll('a[href^="#"]').forEach(a=>{
        a.addEventListener('click',e=>{
            const target=document.querySelector(a.getAttribute('href'));
            if(target){e.preventDefault();target.scrollIntoView({behavior:'smooth'});}
        });
    });
}

// === INIT ===
function init(){
    initLang();
    initTilt();
    initHeroCard();
    initParticles();
    initReveal();
    initSmoothScroll();
}
if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',init);
else init();
})();